### ISSUE TITLE
Sent to work via France

### ISSUE THREAD

**Issue by riddledaxis** [ljmerza/travel-time-card#15]
I live approximately 40 miles from my office in the UK, and my work and home zones display correctly on the HA map.

But when I configure the travel time card as follows, I am being routed via France for some reason.

To create my Waze sensors I have the following in my configuration.yaml

```
sensor:
  - platform: waze_travel_time
    name: "To Work"
    origin: Zone.home
    destination: zone.paul_work
    realtime: true
    region: 'EU'
  - platform: waze_travel_time
    name: "To Home"
    origin: Zone.paul.work
    destination: zone.home
    realtime: true
    region: 'EU'
```

My travel-time card config is:
```
entities:
  - entity: device_tracker.life360.paul
  - entity: sensor.to_work
    zone: zone.paul_work
  - entity: sensor.to_home
    zone: zone.home
map: waze
type: 'custom:travel-time-card'
```
![travel-time-card route](https://user-images.githubusercontent.com/47009467/77258178-cbd39700-6c70-11ea-87b3-fe57c4799e6e.png)

Any idea what I am doing wrong?

Thanks

Paul
