### ISSUE TITLE
Interaction with monster-card

### ISSUE THREAD

**Issue by OppyLock** [ljmerza/travel-time-card#3]
I was hoping to get this card to auto-populate with a filtered selection of sensors.  I currently use an entities card to show potential active routes, like this:

card:
..show_header_toggle: false
..title: Travel Times
..type: entities
filter:
..include:
....- attributes:
........duration: '> 2'
........domain: sensor
show_empty: false
type: 'custom:monster-card'

This gets me a card showing the travel times of potential trips.  If I change line 4 to type: 'custom:travel-time-card' then I get nothing at all in lovelace.  The travel-time-card works if I manually populate the entities though.

**Comment by ljmerza** [comment]
Are you asking for support for a filter option?

**Comment by ljmerza** [comment]
just leaving a note here for myself

```
- card:
          show_header_toggle: false
          title: Travel Times
          type: custom-travel-time-card
        filter:
          include:
            - attributes:
                duration:  '<= 0'
        type: 'custom:monster-card'
```
